openmp1: openmp1.cpp
	g++ -g -Wall -fopenmp -std=c++11 -o $@ $<

openmp2: openmp2.cpp
	g++ -g -Wall -fopenmp -std=c++11 -o $@ $<

avx_summation: avx_summation.cpp
	g++ -g -O2 -Wall -mavx2 -std=c++11 -o $@ $<